base_local_planner: eband_local_planner/EBandPlannerROS



EBandPlannerROS:
  Ctrl_Rate: 10.0
  bubble_velocity_multiplier: 2.0
  costmap_weight: 10.0
  differential_drive: false
  disallow_hysteresis: false
  eband_equilibrium_approx_max_recursion_depth: 4
  eband_equilibrium_relative_overshoot: 0.75
  eband_external_force_gain: 2.0
  eband_internal_force_gain: 1.0
  eband_min_relative_overlap: 0.7
  eband_significant_force_lower_bound: 0.15
  eband_tiny_bubble_distance: 0.01
  eband_tiny_bubble_expansion: 0.01
  in_place_trans_vel: 0.0
  k_damp: 4.6
  k_prop: 1000
  marker_lifetime: 0.5
  max_acceleration: 2.5
  max_rotational_acceleration: 0
  max_translational_acceleration: 2.5
  max_vel_lin: 2
  max_vel_th: 0
  min_in_place_vel_th: 0.0
  min_vel_lin: 0.1
  min_vel_th: 0.0
  num_iterations_eband_optimization: 3
  rot_stopped_vel: 0.01
  rotation_correction_threshold: 0.5
  rotation_threshold_multiplier: 1.0
  trans_stopped_vel: 0.01
  virtual_mass: 0.2
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 6.24