global_costmap:
 
  global_frame: world
  robot_base_frame: $(arg namespace)/base_link
  update_frequency: 5
  static_map: false
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 255
  allow_unknown: false
  observation_persistence: 0
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  static_layer:
    enabled: true
    map_topic: "/filtered_map"
    track_unknown_space: true

  inflation_layer:
    inflation_radius: 1
    cost_scaling_factor: 2.0
    inflate_unknown: true
 
    