global_costmap:
 
  global_frame: world
  robot_base_frame: $(arg namespace)/base_link
  update_frequency: 5
  static_map: false
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 255
  allow_unknown: false
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  static_layer:
    enabled: true
    map_topic: "/filtered_map"
    track_unknown_space: true

  inflation_layer:
    inflation_radius: 1
    cost_scaling_factor: 3.0
    inflate_unknown: true
  obstacle_layer:
    enabled: true
    observation_sources: point_cloud_sensor
    track_unknown_space: true
    point_cloud_sensor: {
      sensor_frame: $(arg namespace)/velodyne_base_link,
      data_type: PointCloud2,
      topic: /$(arg namespace)/velodyne_points,
      marking: true,
      clearing: true,
      obstacle_range: 60,
      min_obstacle_height: 0.5
      }
    