global_costmap:
  global_frame: world
  robot_base_frame: $(arg namespace)/base_link
  update_frequency: 4
  static_map: false
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 255
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  static_layer:
    enabled: true
    map_topic: "/$(arg namespace)/projected_map"