local_costmap:
  global_frame: world
  robot_base_frame: $(arg namespace)/base_link
  update_frequency: 5
  publish_frequency: 1
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  resolution: 0.08
  neutral_cost: 66
  lethal_cost: 255
  
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
     
  static_layer:
    enabled: true
    map_topic: "/$(arg namespace)/projected_map"
    track_unknown_space: true
  obstacle_layer:
    enabled: true
    observation_sources: point_cloud_sensor
    track_unknown_space: true
    point_cloud_sensor: {
      sensor_frame: $(arg namespace)/velodyne_base_link,
      data_type: PointCloud2,
      topic: /$(arg namespace)/velodyne_points,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.7,
      obstacle_range: 15
      }
  inflation_layer:
    inflation_radius: 0.6
    cost_scaling_factor: 3.0
    inflate_unknown: true